lib/ip: calculate SO_RCVBUFFORCE limit more accurately
Xilinx-CNS/onload pull request #239
Opened 2024-08-16 12:19 UTC by okt-sergeyn

Do not allow socket receive buffer size to exceed maximum number of RX packets.

2024-08-16 12:31 UTC, ol-alexandra commented
This patch tells: it we have one socket, then it should not consume all RX packets from the stack.  But this patch allows to consume all RX packets using 2 sockets.  I.e. the patch is an improvement comparing to #232.  But I'm not sure that the number "2" is well-chosen.

2024-08-16 12:31 UTC, ol-alexandra approved these changes

2024-08-16 17:10 UTC, okt-sergeyn commented
> This patch tells: it we have one socket, then it should not consume all RX packets from the stack. But this patch allows to consume all RX packets using 2 sockets. I.e. the patch is an improvement comparing to #232. But I'm not sure that the number "2" is well-chosen.

Thanks for the note.
Looking at the further code
```c
    s->so.rcvbuf = CI_MAX(oo_adjust_SO_XBUF(v), (int) NI_OPTS(netif).tcp_rcvbuf_min);
```
```c
/* src/lib/transport/ip/ip_internal.h */
#define oo_adjust_SO_XBUF(v)  ((v) * 2)
```
The value is doubled afterwards. So we still can consume all RX packets with single socket.
I believe this "/2" is needed to meet socket API.

2024-08-21 09:56 UTC, ivatet-amd commented
I assumed `max_rx_packets` and `pkt_sets_max` are related, i.e. one is a function of the other. Thus it looks like further clarification of https://github.com/Xilinx-CNS/onload/pull/232/ and OK.

What about `SO_SNDBUFFORCE` and `max_tx_packets`? Would this patch apply the same way to TX?

2024-08-21 09:57 UTC, ivatet-amd approved these changes

2024-08-23 06:20 UTC, ol-alexandra commented
> The value is doubled afterwards. So we still can consume all RX packets with single socket. I believe this "/2" is needed to meet socket API.

Could you please change your "/2" to something like "/5"?  I believe it is completely wrong that one socket can consume all the RX packets leaving no packets for RX ring.

2024-08-23 06:21 UTC, ol-alexandra requested changes
Please change "/2" -> "/5"

2024-09-02 10:18 UTC, ivatet-amd commented
@ol-alexandra Shall we worry about the existing users if we reduce the limit?

I suppose we're waiting for @okt-sergeyn to come back to the PR. In addition to `/2` and `SO_SNDBUFFORCE` comments, may I ask to describe a couple of use cases demonstrating the changes in action? Is it a no-op as-is?

2024-09-02 18:34 UTC, okt-sergeyn commented
Use the same approach for TX.
Replace "/2" with bigger numbers.
@ol-alexandra please confirm that I got your idea right.

2024-09-02 19:10 UTC, ol-alexandra approved these changes

2024-09-03 12:18 UTC, merged